border_width = 2
margin = [4, 4]
default_border_color = "#12131b"
floating_border_color = "#CBAEBB"
focused_border_color = "#ced1da"


col1 = "#3A5781"
col2 = "#68718E"
col3 = "#B36A8B"
col4 = "#7986A6"
col5 = "#9B9BAA"
col6 = "#CBAEBB"
col7 = "#ced1da"
col8 = "#909298"
col9 = "#3A5781"
col10 = "#68718E"
col11 = "#B36A8B"
col12 = "#7986A6"
col13 = "#9B9BAA"
col14 = "#CBAEBB"
col15 = "#ced1da"



background = "#12131b"
foreground = "#ced1da"
