border_width = 2
margin = [4, 4]
default_border_color = "#0e1113"
floating_border_color = "#D2675C"
focused_border_color = "#e9b0a5"


col1 = "#8B453B"
col2 = "#8F5456"
col3 = "#AE5A59"
col4 = "#AC635D"
col5 = "#897A78"
col6 = "#D2675C"
col7 = "#e9b0a5"
col8 = "#a37b73"
col9 = "#8B453B"
col10 = "#8F5456"
col11 = "#AE5A59"
col12 = "#AC635D"
col13 = "#897A78"
col14 = "#D2675C"
col15 = "#e9b0a5"



background = "#0e1113"
foreground = "#e9b0a5"
