border_width = 2
margin = [4, 4]
default_border_color = "#252227"
floating_border_color = "#E3A29A"
focused_border_color = "#f0ccca"


col1 = "#DF9B76"
col2 = "#977A82"
col3 = "#B78F98"
col4 = "#B58F9C"
col5 = "#C89698"
col6 = "#E3A29A"
col7 = "#f0ccca"
col8 = "#a88e8d"
col9 = "#DF9B76"
col10 = "#977A82"
col11 = "#B78F98"
col12 = "#B58F9C"
col13 = "#C89698"
col14 = "#E3A29A"
col15 = "#f0ccca"



background = "#252227"
foreground = "#f0ccca"
